### ISSUE TITLE
Some Htmlwidgets do not display

### ISSUE THREAD

**Issue by cyclingdata** [rstudio/flexdashboard#156]
I have a flexdashboard template and  I use knitr's render function with params to create multiple dashboards with the same format. 
About half of the dashboards display completely as expected, and the other half miss about one third of the htmlwidgets. In theses cases, always the same spots are missing (in three differents pages). No errors, just blank spots where the htmlwidgets are supposed to be, except for the titles. Missing htmlwidgets are from highcharts or DT (in fact, all from DT are missing).

I already have tried to : 
- knit directly the flexdashboard in RStudio with issue parameters : same problem happens
- run code block by block in Rstudio with issue parameters: each widget displays properly
- remove some pages (I have 11 in the template) where there is no issue, then suddenly the htmlwidgets display correctly ! For example, my pages are called A - B - C - D... and my problem occurs on pages B and D. I remove code from page C, now pages B and D are ok ! 
-run multiple times the render function with the same parameters, it is always the same parameters that generate problems

What can explain this behaviour ? Are my files too big ? They contain 11 pages and about 50 htmlwidgets.
Thank you !

**Comment by bborgesr** [comment]
What's the output that you get if you run `devtools::session_info()`?

 Try installing knitr, rmarkdown and flexdashboard from github (e.g. `devtools::install_github("rstudio/flexdashboard")`) and running your app again. There was a recent bug in `knitr` just was just fixed hours ago (https://github.com/yihui/knitr/commit/f37911941a9fe57bce44ae5d1bb0c661eaa05fc8)...

Also, which version of pandoc are you using (`rmarkdown::pandoc_version()`)? If it's over 2.0, can you revert back to 1.9 and see if that fixes it? We've been having lots of Pandoc 2.0 compatibility issues, so my guess is that this is another instance of it. If not, it would help a lot if you can come up with a minimal reproducible example.

**Comment by bborgesr** [comment]
Also check issue #155, and see if that's representative of the problem you're experiencing.

**Comment by cyclingdata** [comment]
Thank you for your quick response, I have installed the packages from Github, I will let you know if that solves my problem. It takes some time for my code to run.

My pandoc version is 1.17.2

My session info is : 

     setting  value                       
     version  R version 3.4.0 (2017-04-21)
     system   x86_64, mingw32             
     ui       RStudio (1.0.143)           
     language (EN)                        
     collate  French_France.1252          
     tz       Europe/Paris                
     date     2017-11-17                  

and a lot of packages after, do you need them too ?

It is difficult to provide a minimal reproducible example because the problem only appears when I have a lot of pages / htmlwidgets. But this is different from #155 , I have captures from expected output and current output

Expected (what I have when I remove some of the pages) : 
![expected_output](https://user-images.githubusercontent.com/8535883/32954689-1b38a28c-cbb4-11e7-8798-da789136537b.PNG)

Current :
![current_output](https://user-images.githubusercontent.com/8535883/32954677-12886622-cbb4-11e7-9715-6412e5443020.PNG)

**Comment by bborgesr** [comment]
Can you tell me which are the packages you left in the app and which are the ones you took out (to get it to display properly)?

**Comment by cyclingdata** [comment]
I didn’t change the packages, all librairies are loaded in my first chunk, I only removed code chunks that displayed other pages. 
I have tried with the github versions of the packages you have mentionned and still have the issue.

**Comment by bborgesr** [comment]
I suggested you should update the packages because I thought this may have been a result of the recent Pandoc 2.0 release. But that doesn't seem to be the case. In any case, instead of using the `sessionInfo()` function you used above, can you instead use `devtools::session_info()` and copy the whole output here? That's the info I'm after.

Aside from that, unfortunately, without a repro, there isn't much I can do. See [this article](https://shiny.rstudio.com/articles/help.html) for tips on writing a minimal reproducible example.

**Comment by cyclingdata** [comment]
Seems like I found out what was wrong.
I had a widget with this code : 

     highchart() %>% 
     hc_chart(type = "bar")  %>%
     hc_xAxis(categories = as.character(df$d_detail_action[1:5])) %>%
     hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%  
     hc_add_series(data=df$nb_telech[1:5],name="Téléchargements") 

The problem was sometimes df contained less than 5 rows. What surprise me is this widget was not the first one which caused the problem. Anyway it works now !
Thank you for your help and your time !
