### ISSUE TITLE
Unable to add vertical scroll on Inputs {.sidebar}

### ISSUE THREAD

**Issue by bridgeportbyron** [rstudio/flexdashboard#27]
I am designing a Flexdashboard UI with 17 user inputs, most of them are textbox one is a checkbox and an actionbutton. I can only see 10 textbox when I run the script I cannot see the rest and i cannot find any documentation that describes how to add vertical scroll on Input {.sidebar}. Here's my code below.

```
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

    ```{r setup, include=FALSE}
     library(flexdashboard)
     ```

  Inputs {.sidebar}
-----------------------------------------------------------------------

  ```{r}
library(shiny)
library(shinyjs)


shinyjs::useShinyjs()
#tags$hr(),
shinyjs::disabled(textInput("id", "Id", "0"))
textInput("X1", "X1", "")
textInput("X2", "X2", "")
textInput("X3", "X3", "")
textInput("X4", "X4", "")
textInput("X5", "X5", "")
textInput("X6", "X6", "")
textInput("X7", "X7", "")
textInput("X8", "X8", "")
textInput("X9", "X9", "")
textInput("X10", "X10", "")
textInput("X11", "X11", "")
textInput("X12", "X12", "")

textInput("X13", "X13", "")
textInput("X14", "X14", "")
textInput("X15", "X15", "")
textInput("X16", "X16", "")

checkboxInput("X17", "X17", FALSE)


#action buttons
actionButton("submit", "Submit Changes")


```
```

**Comment by jjallaire** [comment]
Fixed via: https://github.com/rstudio/flexdashboard/commit/440cab3e9d5f68b44b9f73110be9a04d0635a612

You can use a version with the fix by installing from GitHub:

```r
devtools::install_github("rstudio/flexdsahboard")
```

Alternatively, you could add this snippet of CSS to your dashboard:

```html
<style type="text/css"> .sidebar { overflow: auto; } </style>
```

**Comment by MahreenAthar** [comment]
@jjallaire Hi I'm very new to this. Can you tell how i can add this snippet to my dashboard: 
`<style type="text/css"> .sidebar { overflow: auto; } </style>`
Do i have to make some kind of separate css style sheet?

**Comment by jjallaire** [comment]
The latest version from CRAN has this fix so that's one option.

If you need to include the code directly you can just add that code to the Rmd (no separate CSS file required)

**Comment by MahreenAthar** [comment]
@jjallaire I added the snippet directly to Rmd and now i have a scroll bar but it still isn't showing the entire graph that i made. This is what it shows:  
![capture](https://user-images.githubusercontent.com/39671939/43356364-ed8f49e8-9288-11e8-8aa6-d1de997c4283.PNG)
It's showing the code too. Plus when i scroll down it doesn't show me the full graph 
![capture1](https://user-images.githubusercontent.com/39671939/43356369-032c80e0-9289-11e8-9672-1bab121691df.PNG)
see here it's showing the y-axis but not the x-axis.
Here's my code:
`---
title: "DataScience: The Upcoming Revolution"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
```
```
    <style type="text/css"> .sidebar { overflow: auto; } </style>
```
DataScience 101 {.storyboard}
=====================================

    
### What Is DataScience?`

**Comment by jjallaire** [comment]
I guess you prefer to run the 2 year old version of flexdashboard? (the newer version has this code in it already).

I also don't see a sidebar in your dashboard so I don't know that this fix actually has anything to do with your use case.

**Comment by MahreenAthar** [comment]
Oh okay.
